'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload", ConfigurationName:="IAuthenticateDownloadService")>  _
Public Interface IAuthenticateDownloadService
    
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload/IAuthenticat"& _ 
        "eDownloadService/AuthenticateDownload", ReplyAction:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload/IAuthenticat"& _ 
        "eDownloadService/AuthenticateDownloadResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Document))>  _
    Function AuthenticateDownload(ByVal Request As DownloadAuthenticationRequest) As DownloadAuthenticationResult
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload")>  _
Partial Public Class DownloadAuthenticationRequest
    
    Private contextIdentifierField As System.Guid
    
    Private documentIdField As System.Guid
    
    Private authTokenField As System.Guid
    
    Private passwordField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ContextIdentifier() As System.Guid
        Get
            Return Me.contextIdentifierField
        End Get
        Set
            Me.contextIdentifierField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property DocumentId() As System.Guid
        Get
            Return Me.documentIdField
        End Get
        Set
            Me.documentIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property AuthToken() As System.Guid
        Get
            Return Me.authTokenField
        End Get
        Set
            Me.authTokenField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class AsyncSubmissionResult
    
    Private exceptionsField() As DocumentException
    
    Private sessionIdField As System.Guid
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
    Public Property Exceptions() As DocumentException()
        Get
            Return Me.exceptionsField
        End Get
        Set
            Me.exceptionsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SessionId() As System.Guid
        Get
            Return Me.sessionIdField
        End Get
        Set
            Me.sessionIdField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class DocumentException
    
    Private severityField As ExceptionSeverity
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Severity() As ExceptionSeverity
        Get
            Return Me.severityField
        End Get
        Set
            Me.severityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Public Enum ExceptionSeverity
    
    '''<remarks/>
    Warning
    
    '''<remarks/>
    [Error]
    
    '''<remarks/>
    Fatal
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class DocumentResult
    
    Private metadataField As Metadata
    
    Private exceptionsField() As DocumentException
    
    Private idField As System.Guid
    
    Private idFieldSpecified As Boolean
    
    Private authTokenField As System.Guid
    
    Private authTokenFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property Metadata() As Metadata
        Get
            Return Me.metadataField
        End Get
        Set
            Me.metadataField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Order:=1)>  _
    Public Property Exceptions() As DocumentException()
        Get
            Return Me.exceptionsField
        End Get
        Set
            Me.exceptionsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As System.Guid
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property IdSpecified() As Boolean
        Get
            Return Me.idFieldSpecified
        End Get
        Set
            Me.idFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property AuthToken() As System.Guid
        Get
            Return Me.authTokenField
        End Get
        Set
            Me.authTokenField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AuthTokenSpecified() As Boolean
        Get
            Return Me.authTokenFieldSpecified
        End Get
        Set
            Me.authTokenFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class Metadata
    
    Private userNameField As String
    
    Private documentNameField As String
    
    Private orderNumberField As String
    
    Private passwordField As String
    
    Private expirationDateField As Date
    
    Private expirationDateFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UserName() As String
        Get
            Return Me.userNameField
        End Get
        Set
            Me.userNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property DocumentName() As String
        Get
            Return Me.documentNameField
        End Get
        Set
            Me.documentNameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property OrderNumber() As String
        Get
            Return Me.orderNumberField
        End Get
        Set
            Me.orderNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
    Public Property ExpirationDate() As Date
        Get
            Return Me.expirationDateField
        End Get
        Set
            Me.expirationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ExpirationDateSpecified() As Boolean
        Get
            Return Me.expirationDateFieldSpecified
        End Get
        Set
            Me.expirationDateFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class FileRetrievalCredential
    
    Private usernameField As String
    
    Private passwordField As String
    
    Private domainField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Username() As String
        Get
            Return Me.usernameField
        End Get
        Set
            Me.usernameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Password() As String
        Get
            Return Me.passwordField
        End Get
        Set
            Me.passwordField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Domain() As String
        Get
            Return Me.domainField
        End Get
        Set
            Me.domainField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class UnderlyingFileMetadata
    
    Private credentialField As FileRetrievalCredential
    
    Private retrievalMethodField As FileRetrievalMethod
    
    Private urlField As String
    
    Private fileTypeField As SupportedFileType
    
    Private requiresAuthenticationField As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property Credential() As FileRetrievalCredential
        Get
            Return Me.credentialField
        End Get
        Set
            Me.credentialField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RetrievalMethod() As FileRetrievalMethod
        Get
            Return Me.retrievalMethodField
        End Get
        Set
            Me.retrievalMethodField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Url() As String
        Get
            Return Me.urlField
        End Get
        Set
            Me.urlField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property FileType() As SupportedFileType
        Get
            Return Me.fileTypeField
        End Get
        Set
            Me.fileTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RequiresAuthentication() As Boolean
        Get
            Return Me.requiresAuthenticationField
        End Get
        Set
            Me.requiresAuthenticationField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Public Enum FileRetrievalMethod
    
    '''<remarks/>
    BasicHttp
    
    '''<remarks/>
    SalesforceApi
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Public Enum SupportedFileType
    
    '''<remarks/>
    PDF
    
    '''<remarks/>
    DOC
    
    '''<remarks/>
    DOCX
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class UnderlyingFile
    
    Private dataField() As Byte
    
    Private fileTypeField As SupportedFileType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
    Public Property Data() As Byte()
        Get
            Return Me.dataField
        End Get
        Set
            Me.dataField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property FileType() As SupportedFileType
        Get
            Return Me.fileTypeField
        End Get
        Set
            Me.fileTypeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class Parameter
    
    Private nameField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class Template
    
    Private parametersField() As Parameter
    
    Private idField As System.Guid
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
    Public Property Parameters() As Parameter()
        Get
            Return Me.parametersField
        End Get
        Set
            Me.parametersField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Id() As System.Guid
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(FileRetrievalDocument)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(FileDocument)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class Document
    
    Private metadataField As Metadata
    
    Private templateField As Template
    
    Private contextIdentifierField As System.Guid
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property Metadata() As Metadata
        Get
            Return Me.metadataField
        End Get
        Set
            Me.metadataField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
    Public Property Template() As Template
        Get
            Return Me.templateField
        End Get
        Set
            Me.templateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ContextIdentifier() As System.Guid
        Get
            Return Me.contextIdentifierField
        End Get
        Set
            Me.contextIdentifierField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class FileRetrievalDocument
    Inherits Document
    
    Private underlyingFileMetadataField As UnderlyingFileMetadata
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property UnderlyingFileMetadata() As UnderlyingFileMetadata
        Get
            Return Me.underlyingFileMetadataField
        End Get
        Set
            Me.underlyingFileMetadataField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit")>  _
Partial Public Class FileDocument
    Inherits Document
    
    Private underlyingFileField As UnderlyingFile
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property UnderlyingFile() As UnderlyingFile
        Get
            Return Me.underlyingFileField
        End Get
        Set
            Me.underlyingFileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload")>  _
Partial Public Class DownloadAuthenticationException
    
    Private severityField As DownloadAuthenticationExceptionSeverity
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Severity() As DownloadAuthenticationExceptionSeverity
        Get
            Return Me.severityField
        End Get
        Set
            Me.severityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload")>  _
Public Enum DownloadAuthenticationExceptionSeverity
    
    '''<remarks/>
    Warning
    
    '''<remarks/>
    [Error]
    
    '''<remarks/>
    Fatal
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/AuthenticateDownload")>  _
Partial Public Class DownloadAuthenticationResult
    
    Private exceptionsField() As DownloadAuthenticationException
    
    Private sessionIdField As System.Guid
    
    Private sessionIdFieldSpecified As Boolean
    
    Private documentIdField As System.Guid
    
    Private documentIdFieldSpecified As Boolean
    
    Private expirationDateField As Date
    
    Private expirationDateFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayAttribute(Order:=0)>  _
    Public Property Exceptions() As DownloadAuthenticationException()
        Get
            Return Me.exceptionsField
        End Get
        Set
            Me.exceptionsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property SessionId() As System.Guid
        Get
            Return Me.sessionIdField
        End Get
        Set
            Me.sessionIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property SessionIdSpecified() As Boolean
        Get
            Return Me.sessionIdFieldSpecified
        End Get
        Set
            Me.sessionIdFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property DocumentId() As System.Guid
        Get
            Return Me.documentIdField
        End Get
        Set
            Me.documentIdField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DocumentIdSpecified() As Boolean
        Get
            Return Me.documentIdFieldSpecified
        End Get
        Set
            Me.documentIdFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ExpirationDate() As Date
        Get
            Return Me.expirationDateField
        End Get
        Set
            Me.expirationDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ExpirationDateSpecified() As Boolean
        Get
            Return Me.expirationDateFieldSpecified
        End Get
        Set
            Me.expirationDateFieldSpecified = value
        End Set
    End Property
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface IAuthenticateDownloadServiceChannel
    Inherits IAuthenticateDownloadService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class AuthenticateDownloadServiceClient
    Inherits System.ServiceModel.ClientBase(Of IAuthenticateDownloadService)
    Implements IAuthenticateDownloadService
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function AuthenticateDownload(ByVal Request As DownloadAuthenticationRequest) As DownloadAuthenticationResult Implements IAuthenticateDownloadService.AuthenticateDownload
        Return MyBase.Channel.AuthenticateDownload(Request)
    End Function
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.assuresign.net/Services/DocumentNOW/Submit", ConfigurationName:="ISubmitService")>  _
Public Interface ISubmitService
    
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/SubmitWithF"& _ 
        "ile", ReplyAction:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/SubmitWithF"& _ 
        "ileResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Document))>  _
    Function SubmitWithFile(ByVal Documents() As FileDocument) As DocumentResult()
    
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/AsyncSubmit"& _ 
        "WithFile", ReplyAction:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/AsyncSubmit"& _ 
        "WithFileResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Document))>  _
    Function AsyncSubmitWithFile(ByVal Documents() As FileDocument) As AsyncSubmissionResult
    
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/SubmitWithF"& _ 
        "ileRetrieval", ReplyAction:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/SubmitWithF"& _ 
        "ileRetrievalResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Document))>  _
    Function SubmitWithFileRetrieval(ByVal Documents() As FileRetrievalDocument) As DocumentResult()
    
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/AsyncSubmit"& _ 
        "WithFileRetrieval", ReplyAction:="https://www.assuresign.net/Services/DocumentNOW/Submit/ISubmitService/AsyncSubmit"& _ 
        "WithFileRetrievalResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Document))>  _
    Function AsyncSubmitWithFileRetrieval(ByVal Documents() As FileRetrievalDocument) As AsyncSubmissionResult
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface ISubmitServiceChannel
    Inherits ISubmitService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class SubmitServiceClient
    Inherits System.ServiceModel.ClientBase(Of ISubmitService)
    Implements ISubmitService
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Function SubmitWithFile(ByVal Documents() As FileDocument) As DocumentResult() Implements ISubmitService.SubmitWithFile
        Return MyBase.Channel.SubmitWithFile(Documents)
    End Function
    
    Public Function AsyncSubmitWithFile(ByVal Documents() As FileDocument) As AsyncSubmissionResult Implements ISubmitService.AsyncSubmitWithFile
        Return MyBase.Channel.AsyncSubmitWithFile(Documents)
    End Function
    
    Public Function SubmitWithFileRetrieval(ByVal Documents() As FileRetrievalDocument) As DocumentResult() Implements ISubmitService.SubmitWithFileRetrieval
        Return MyBase.Channel.SubmitWithFileRetrieval(Documents)
    End Function
    
    Public Function AsyncSubmitWithFileRetrieval(ByVal Documents() As FileRetrievalDocument) As AsyncSubmissionResult Implements ISubmitService.AsyncSubmitWithFileRetrieval
        Return MyBase.Channel.AsyncSubmitWithFileRetrieval(Documents)
    End Function
End Class
