IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblNachaRegister' AND COLUMN_NAME = 'KeepInGCA')
	BEGIN
		ALTER TABLE tblNachaRegister ADD KeepInGCA BIT;
	END
GO
IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'tblNachaRegister2' AND COLUMN_NAME = 'KeepInGCA')
	BEGIN
		ALTER TABLE tblNachaRegister2 ADD KeepInGCA BIT;
	END
GO 