Delete from tblDialerCallResultType
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(1,	'Answered',	120,	'Answered by Person')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(2,	'Machine',	120,	'VoiceMail (No Message Left)')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(3,	'Message',	120,	'Left Message')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(4,	'NoAnswer',	60,	'No Answered')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(5,	'Busy',	10,	'Busy Signal')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(6,	'Error',	1440,	'Error')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(7,	'Cancelled',	10,	'Cancelled')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(8,	'BadNumber',	10,	'Bad Number')
Insert Into tblDialerCallResultType(ResultTypeId, Result, DefaultExpiration, Description)
Values(9,	'NumberDisconnected',	10,	'Disconnected Number')