'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.3pv.net/webservices/", ConfigurationName:="ThreePVWebServicesSoap")>  _
Public Interface ThreePVWebServicesSoap
    
    'CODEGEN: Generating message contract since element name requestXML from namespace https://www.3pv.net/webservices/ is not marked nillable
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.3pv.net/webservices/directXML", ReplyAction:="*")>  _
    Function directXML(ByVal request As directXMLRequest) As directXMLResponse
    
    'CODEGEN: Generating message contract since element name requestXML from namespace https://www.3pv.net/webservices/ is not marked nillable
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.3pv.net/webservices/directXMLCustom", ReplyAction:="*")>  _
    Function directXMLCustom(ByVal request As directXMLCustomRequest) As directXMLCustomResponse
    
    'CODEGEN: Generating message contract since element name requestXML from namespace https://www.3pv.net/webservices/ is not marked nillable
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.3pv.net/webservices/directXMLTest", ReplyAction:="*")>  _
    Function directXMLTest(ByVal request As directXMLTestRequest) As directXMLTestResponse
    
    'CODEGEN: Generating message contract since element name requestXML from namespace https://www.3pv.net/webservices/ is not marked nillable
    <System.ServiceModel.OperationContractAttribute(Action:="https://www.3pv.net/webservices/directXMLCustomTest", ReplyAction:="*")>  _
    Function directXMLCustomTest(ByVal request As directXMLCustomTestRequest) As directXMLCustomTestResponse
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXML", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLRequestBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLRequestBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLRequestBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public requestXML As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal requestXML As String)
        MyBase.New
        Me.requestXML = requestXML
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLResponse", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLResponseBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLResponseBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLResponseBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public directXMLResult As System.Xml.XmlElement
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal directXMLResult As System.Xml.XmlElement)
        MyBase.New
        Me.directXMLResult = directXMLResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLCustomRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLCustom", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLCustomRequestBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLCustomRequestBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLCustomRequestBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public requestXML As String
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
    Public vendorID As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal requestXML As String, ByVal vendorID As String)
        MyBase.New
        Me.requestXML = requestXML
        Me.vendorID = vendorID
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLCustomResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLCustomResponse", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLCustomResponseBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLCustomResponseBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLCustomResponseBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public directXMLCustomResult As System.Xml.XmlElement
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal directXMLCustomResult As System.Xml.XmlElement)
        MyBase.New
        Me.directXMLCustomResult = directXMLCustomResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLTestRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLTest", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLTestRequestBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLTestRequestBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLTestRequestBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public requestXML As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal requestXML As String)
        MyBase.New
        Me.requestXML = requestXML
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLTestResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLTestResponse", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLTestResponseBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLTestResponseBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLTestResponseBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public directXMLTestResult As System.Xml.XmlElement
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal directXMLTestResult As System.Xml.XmlElement)
        MyBase.New
        Me.directXMLTestResult = directXMLTestResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLCustomTestRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLCustomTest", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLCustomTestRequestBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLCustomTestRequestBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLCustomTestRequestBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public requestXML As String
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
    Public vendorID As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal requestXML As String, ByVal vendorID As String)
        MyBase.New
        Me.requestXML = requestXML
        Me.vendorID = vendorID
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
Partial Public Class directXMLCustomTestResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute(Name:="directXMLCustomTestResponse", [Namespace]:="https://www.3pv.net/webservices/", Order:=0)>  _
    Public Body As directXMLCustomTestResponseBody
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Body As directXMLCustomTestResponseBody)
        MyBase.New
        Me.Body = Body
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.3pv.net/webservices/")>  _
Partial Public Class directXMLCustomTestResponseBody
    
    <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
    Public directXMLCustomTestResult As System.Xml.XmlElement
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal directXMLCustomTestResult As System.Xml.XmlElement)
        MyBase.New
        Me.directXMLCustomTestResult = directXMLCustomTestResult
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface ThreePVWebServicesSoapChannel
    Inherits ThreePVWebServicesSoap, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class ThreePVWebServicesSoapClient
    Inherits System.ServiceModel.ClientBase(Of ThreePVWebServicesSoap)
    Implements ThreePVWebServicesSoap
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function ThreePVWebServicesSoap_directXML(ByVal request As directXMLRequest) As directXMLResponse Implements ThreePVWebServicesSoap.directXML
        Return MyBase.Channel.directXML(request)
    End Function
    
    Public Function directXML(ByVal requestXML As String) As System.Xml.XmlElement
        Dim inValue As directXMLRequest = New directXMLRequest
        inValue.Body = New directXMLRequestBody
        inValue.Body.requestXML = requestXML
        Dim retVal As directXMLResponse = CType(Me,ThreePVWebServicesSoap).directXML(inValue)
        Return retVal.Body.directXMLResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function ThreePVWebServicesSoap_directXMLCustom(ByVal request As directXMLCustomRequest) As directXMLCustomResponse Implements ThreePVWebServicesSoap.directXMLCustom
        Return MyBase.Channel.directXMLCustom(request)
    End Function
    
    Public Function directXMLCustom(ByVal requestXML As String, ByVal vendorID As String) As System.Xml.XmlElement
        Dim inValue As directXMLCustomRequest = New directXMLCustomRequest
        inValue.Body = New directXMLCustomRequestBody
        inValue.Body.requestXML = requestXML
        inValue.Body.vendorID = vendorID
        Dim retVal As directXMLCustomResponse = CType(Me,ThreePVWebServicesSoap).directXMLCustom(inValue)
        Return retVal.Body.directXMLCustomResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function ThreePVWebServicesSoap_directXMLTest(ByVal request As directXMLTestRequest) As directXMLTestResponse Implements ThreePVWebServicesSoap.directXMLTest
        Return MyBase.Channel.directXMLTest(request)
    End Function
    
    Public Function directXMLTest(ByVal requestXML As String) As System.Xml.XmlElement
        Dim inValue As directXMLTestRequest = New directXMLTestRequest
        inValue.Body = New directXMLTestRequestBody
        inValue.Body.requestXML = requestXML
        Dim retVal As directXMLTestResponse = CType(Me,ThreePVWebServicesSoap).directXMLTest(inValue)
        Return retVal.Body.directXMLTestResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function ThreePVWebServicesSoap_directXMLCustomTest(ByVal request As directXMLCustomTestRequest) As directXMLCustomTestResponse Implements ThreePVWebServicesSoap.directXMLCustomTest
        Return MyBase.Channel.directXMLCustomTest(request)
    End Function
    
    Public Function directXMLCustomTest(ByVal requestXML As String, ByVal vendorID As String) As System.Xml.XmlElement
        Dim inValue As directXMLCustomTestRequest = New directXMLCustomTestRequest
        inValue.Body = New directXMLCustomTestRequestBody
        inValue.Body.requestXML = requestXML
        inValue.Body.vendorID = vendorID
        Dim retVal As directXMLCustomTestResponse = CType(Me,ThreePVWebServicesSoap).directXMLCustomTest(inValue)
        Return retVal.Body.directXMLCustomTestResult
    End Function
End Class
