 USE [master]
GO
/****** Object:  Database [ClientStatements]    Script Date: 01/05/2011 08:30:57 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'ClientStatements')
BEGIN
CREATE DATABASE [ClientStatements] ON  PRIMARY 
( NAME = N'ClientStatements', FILENAME = N'E:\Microsoft SQL Server\MSSQL.1\MSSQL\Data\ClientStatements.mdf' , SIZE = 1068032KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClientStatements_log', FILENAME = N'F:\Microsoft SQL Server\MSSQL.1\MSSQL\Data\ClientStatements_log.ldf' , SIZE = 1024064KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO
EXEC dbo.sp_dbcmptlevel @dbname=N'ClientStatements', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClientStatements].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [ClientStatements] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClientStatements] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClientStatements] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClientStatements] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClientStatements] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClientStatements] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClientStatements] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [ClientStatements] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClientStatements] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClientStatements] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClientStatements] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClientStatements] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClientStatements] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClientStatements] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClientStatements] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClientStatements] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ClientStatements] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClientStatements] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClientStatements] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClientStatements] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClientStatements] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClientStatements] SET  READ_WRITE 
GO
ALTER DATABASE [ClientStatements] SET RECOVERY FULL 
GO
ALTER DATABASE [ClientStatements] SET  MULTI_USER 
GO
ALTER DATABASE [ClientStatements] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClientStatements] SET DB_CHAINING OFF 