IF NOT EXISTS (SELECT * FROM sysobjects WHERE type = 'U' AND name = 'tblHardshipData')
	BEGIN
		CREATE TABLE [dbo].[tblHardshipData](
			[HardshipID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
			[ClientID] [int] NOT NULL,
			[ClientAcctNum] [numeric](18, 0) NOT NULL,
			[HardshipDate] [datetime] NOT NULL CONSTRAINT [DF_tblHardshipData_HardshipDate]  DEFAULT (getdate()),
			[CSR] [varchar](100) NULL,
			[Married] [bit] NULL,
			[Single] [bit] NULL,
			[Divorced] [bit] NULL,
			[Widowed] [bit] NULL,
			[NumChildren] [int] NULL,
			[NumGrandChildren] [int] NULL CONSTRAINT [DF_tblHardshipData_NumGrandChildren]  DEFAULT ((0)),
			[MonthlyIncome_Client_Work] [money] NULL,
			[MonthlyIncome_Client_SocialSecurity] [money] NULL,
			[MonthlyIncome_Client_Disability] [money] NULL,
			[MonthlyIncome_Client_RetirementPension] [money] NULL,
			[MonthlyIncome_Client_SelfEmployed] [money] NULL,
			[MonthlyIncome_Client_Unemployed] [money] NULL,
			[MonthlyIncome_Client_JobDescription] [varchar](50) NULL,
			[MonthlyIncome_Client_FullTime] [bit] NULL,
			[MonthlyIncome_Client_PartTime] [bit] NULL,
			[MonthlyIncome_Spouse_Work] [money] NULL,
			[MonthlyIncome_Spouse_SocialSecurity] [money] NULL,
			[MonthlyIncome_Spouse_Disability] [money] NULL,
			[MonthlyIncome_Spouse_RetirementPension] [money] NULL,
			[MonthlyIncome_Spouse_SelfEmployed] [money] NULL,
			[MonthlyIncome_Spouse_Unemployed] [money] NULL,
			[MonthlyIncome_Spouse_JobDescription] [varchar](50) NULL,
			[MonthlyIncome_Spouse_FullTime] [bit] NULL,
			[MonthlyIncome_Spouse_PartTime] [bit] NULL,
			[MonthlyIncome_IsRecievingStateAssistance] [bit] NULL,
			[MonthlyIncome_IsRecievingStateAssistanceDescription] [varchar](max) NULL,
			[MonthlyExpenses_Rent] [money] NULL,
			[MonthlyExpenses_Mortgage] [money] NULL,
			[MonthlyExpenses_2ndMortgage] [bit] NULL,
			[MonthlyExpenses_2ndMortgageAmt] [money] NULL,
			[MonthlyExpenses_HasClientRefinanced] [bit] NULL,
			[MonthlyExpenses_EquityValueOfHome] [money] NULL,
			[MonthlyExpenses_ReasonForDebt] [varchar](max) NULL,
			[MonthlyExpenses_DoesClientHaveAssets] [bit] NULL,
			[MonthlyExpenses_Carpayment] [money] NULL,
			[MonthlyExpenses_CarInsurance] [money] NULL,
			[MonthlyExpenses_Utilities] [money] NULL,
			[MonthlyExpenses_Groceries] [money] NULL,
			[MonthlyExpenses_MedicalInsurance] [money] NULL,
			[MonthlyExpenses_Medications] [money] NULL,
			[MonthlyExpenses_Gasoline] [money] NULL,
			[MonthlyExpenses_SchoolLoans] [money] NULL,
			[MonthlyExpenses_Other] [money] NULL,
			[MonthlyExpenses_OtherDescription] [varchar](50) NULL,
			[MedicalCondtions_Client_Diabetes] [bit] NULL,
			[MedicalCondtions_Client_Arthritis] [bit] NULL,
			[MedicalCondtions_Client_Asthma] [bit] NULL,
			[MedicalCondtions_Client_HighBloodPressure] [bit] NULL,
			[MedicalCondtions_Client_HighCholesterol] [bit] NULL,
			[MedicalCondtions_Client_Other] [varchar](50) NULL,
			[MedicalCondtions_Client_NumPillsTaken] [int] NULL,
			[MedicalCondtions_Client_History] [varchar](max) NULL,
			[MedicalCondtions_Spouse_Diabetes] [bit] NULL,
			[MedicalCondtions_Spouse_Arthritis] [bit] NULL,
			[MedicalCondtions_Spouse_Asthma] [bit] NULL,
			[MedicalCondtions_Spouse_HighBloodPressure] [bit] NULL,
			[MedicalCondtions_Spouse_HighCholesterol] [bit] NULL,
			[MedicalCondtions_Spouse_Other] [varchar](50) NULL,
			[MedicalCondtions_Spouse_NumPillsTaken] [int] NULL,
			[MedicalCondtions_Spouse_History] [varchar](max) NULL,
			[AdditionalInformation] [varchar](max) NULL,
			[Created] [datetime] NOT NULL CONSTRAINT [DF_tblHardshipData_Created]  DEFAULT (getdate()),
			[CreatedBy] [int] NOT NULL,
			[LastModified] [datetime] NOT NULL CONSTRAINT [DF_tblHardshipData_LastModified]  DEFAULT (getdate()),
			[LastModifiedBy] [int] NOT NULL
		) ON [PRIMARY]
	END
GO


GRANT SELECT ON tblHardshipData TO PUBLIC

