<table cellpadding="0" cellspacing="0" class="menuTable">
    <tr>
        <td>
            <img runat="server" width="8" height="1" src="~/images/spacer.gif" />
        </td>
        <td style="height: 28px; white-space: nowrap">
            <a runat="server" class="menuButton" href="~/clients/enrollment">
                <img runat="server" align="absmiddle" border="0" class="menuButtonImage"
                    src="~/images/16x16_back.png" />Back</a>
        </td>
        <td style="width: 100%;">
            &nbsp;
        </td>
    </tr>
</table>