'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace TUXML.Inquiry

    '
    'This source code was auto-generated by xsd, Version=4.0.30319.17929.
    '
    'Old namespace and XMLTypeAttribute
    '
    '     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2"),
    '     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://api.creditly.co/v2", IsNullable:=False)>
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2"),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://api.creditly.co/v2", IsNullable:=False)>
    Partial Public Class creditBureau

        Private documentField As String

        Private versionField As Decimal

        Private transactionControlField As creditBureauTransactionControl

        Private productField As creditBureauProduct

        '''<remarks/>
        Public Property document() As String
            Get
                Return Me.documentField
            End Get
            Set(value As String)
                Me.documentField = value
            End Set
        End Property

        '''<remarks/>
        Public Property version() As Decimal
            Get
                Return Me.versionField
            End Get
            Set(value As Decimal)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property transactionControl() As creditBureauTransactionControl
            Get
                Return Me.transactionControlField
            End Get
            Set(value As creditBureauTransactionControl)
                Me.transactionControlField = value
            End Set
        End Property

        '''<remarks/>
        Public Property product() As creditBureauProduct
            Get
                Return Me.productField
            End Get
            Set(value As creditBureauProduct)
                Me.productField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControl

        Private userRefNumberField As String

        Private subscriberField As creditBureauTransactionControlSubscriber

        Private optionsField As creditBureauTransactionControlOptions

        '''<remarks/>
        Public Property userRefNumber() As String
            Get
                Return Me.userRefNumberField
            End Get
            Set(value As String)
                Me.userRefNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property subscriber() As creditBureauTransactionControlSubscriber
            Get
                Return Me.subscriberField
            End Get
            Set(value As creditBureauTransactionControlSubscriber)
                Me.subscriberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property options() As creditBureauTransactionControlOptions
            Get
                Return Me.optionsField
            End Get
            Set(value As creditBureauTransactionControlOptions)
                Me.optionsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControlSubscriber

        Private industryCodeField As String

        Private memberCodeField As String

        Private inquirySubscriberPrefixCodeField As String

        Private passwordField As String

        '''<remarks/>
        Public Property industryCode() As String
            Get
                Return Me.industryCodeField
            End Get
            Set(value As String)
                Me.industryCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property memberCode() As String
            Get
                Return Me.memberCodeField
            End Get
            Set(value As String)
                Me.memberCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property inquirySubscriberPrefixCode() As String
            Get
                Return Me.inquirySubscriberPrefixCodeField
            End Get
            Set(value As String)
                Me.inquirySubscriberPrefixCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set(value As String)
                Me.passwordField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControlOptions

        Private processingEnvironmentField As String

        Private countryField As String

        Private languageField As String

        Private contractualRelationshipField As String

        Private pointOfSaleIndicatorField As String

        '''<remarks/>
        Public Property processingEnvironment() As String
            Get
                Return Me.processingEnvironmentField
            End Get
            Set(value As String)
                Me.processingEnvironmentField = value
            End Set
        End Property

        '''<remarks/>
        Public Property country() As String
            Get
                Return Me.countryField
            End Get
            Set(value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set(value As String)
                Me.languageField = value
            End Set
        End Property

        '''<remarks/>
        Public Property contractualRelationship() As String
            Get
                Return Me.contractualRelationshipField
            End Get
            Set(value As String)
                Me.contractualRelationshipField = value
            End Set
        End Property

        '''<remarks/>
        Public Property pointOfSaleIndicator() As String
            Get
                Return Me.pointOfSaleIndicatorField
            End Get
            Set(value As String)
                Me.pointOfSaleIndicatorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProduct

        Private codeField As String

        Private subjectField As creditBureauProductSubject

        Private responseInstructionsField As creditBureauProductResponseInstructions

        Private permissiblePurposeField As creditBureauProductPermissiblePurpose

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property subject() As creditBureauProductSubject
            Get
                Return Me.subjectField
            End Get
            Set(value As creditBureauProductSubject)
                Me.subjectField = value
            End Set
        End Property

        '''<remarks/>
        Public Property responseInstructions() As creditBureauProductResponseInstructions
            Get
                Return Me.responseInstructionsField
            End Get
            Set(value As creditBureauProductResponseInstructions)
                Me.responseInstructionsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property permissiblePurpose() As creditBureauProductPermissiblePurpose
            Get
                Return Me.permissiblePurposeField
            End Get
            Set(value As creditBureauProductPermissiblePurpose)
                Me.permissiblePurposeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubject

        Private numberField As String

        Private subjectRecordField As creditBureauProductSubjectSubjectRecord

        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property subjectRecord() As creditBureauProductSubjectSubjectRecord
            Get
                Return Me.subjectRecordField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecord)
                Me.subjectRecordField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecord

        Private indicativeField As creditBureauProductSubjectSubjectRecordIndicative

        Private addOnProductField As creditBureauProductSubjectSubjectRecordAddOnProduct

        '''<remarks/>
        Public Property indicative() As creditBureauProductSubjectSubjectRecordIndicative
            Get
                Return Me.indicativeField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicative)
                Me.indicativeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property addOnProduct() As creditBureauProductSubjectSubjectRecordAddOnProduct
            Get
                Return Me.addOnProductField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordAddOnProduct)
                Me.addOnProductField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicative

        Private nameField As creditBureauProductSubjectSubjectRecordIndicativeName

        Private addressField As creditBureauProductSubjectSubjectRecordIndicativeAddress

        Private socialSecurityField As creditBureauProductSubjectSubjectRecordIndicativeSocialSecurity

        Private dateOfBirthField As Date

        '''<remarks/>
        Public Property name() As creditBureauProductSubjectSubjectRecordIndicativeName
            Get
                Return Me.nameField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeName)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property address() As creditBureauProductSubjectSubjectRecordIndicativeAddress
            Get
                Return Me.addressField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeAddress)
                Me.addressField = value
            End Set
        End Property

        '''<remarks/>
        Public Property socialSecurity() As creditBureauProductSubjectSubjectRecordIndicativeSocialSecurity
            Get
                Return Me.socialSecurityField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeSocialSecurity)
                Me.socialSecurityField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
        Public Property dateOfBirth() As Date
            Get
                Return Me.dateOfBirthField
            End Get
            Set(value As Date)
                Me.dateOfBirthField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeName

        Private personField As creditBureauProductSubjectSubjectRecordIndicativeNamePerson

        '''<remarks/>
        Public Property person() As creditBureauProductSubjectSubjectRecordIndicativeNamePerson
            Get
                Return Me.personField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeNamePerson)
                Me.personField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeNamePerson

        Private firstField As String

        Private middleField As String

        Private lastField As String

        '''<remarks/>
        Public Property first() As String
            Get
                Return Me.firstField
            End Get
            Set(value As String)
                Me.firstField = value
            End Set
        End Property

        '''<remarks/>
        Public Property middle() As String
            Get
                Return Me.middleField
            End Get
            Set(value As String)
                Me.middleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property last() As String
            Get
                Return Me.lastField
            End Get
            Set(value As String)
                Me.lastField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeAddress

        Private statusField As String

        Private streetField As creditBureauProductSubjectSubjectRecordIndicativeAddressStreet

        Private locationField As creditBureauProductSubjectSubjectRecordIndicativeAddressLocation

        '''<remarks/>
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set(value As String)
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        Public Property street() As creditBureauProductSubjectSubjectRecordIndicativeAddressStreet
            Get
                Return Me.streetField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeAddressStreet)
                Me.streetField = value
            End Set
        End Property

        '''<remarks/>
        Public Property location() As creditBureauProductSubjectSubjectRecordIndicativeAddressLocation
            Get
                Return Me.locationField
            End Get
            Set(value As creditBureauProductSubjectSubjectRecordIndicativeAddressLocation)
                Me.locationField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeAddressStreet
        Private unparsedField As String

        Private numberField As String

        Private nameField As String

        Private preDirectionalField As String

        Private typeField As String

        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property preDirectional() As String
            Get
                Return Me.preDirectionalField
            End Get
            Set(value As String)
                Me.preDirectionalField = value
            End Set
        End Property

        '''<remarks/>
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = value
            End Set
        End Property

        Public Property unparsed() As String
            Get
                Return Me.unparsedField
            End Get
            Set(value As String)
                Me.unparsedField = value
            End Set
        End Property

    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeAddressLocation

        Private cityField As String

        Private stateField As String

        Private zipCodeField As String

        '''<remarks/>
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set(value As String)
                Me.cityField = value
            End Set
        End Property

        '''<remarks/>
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set(value As String)
                Me.stateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property zipCode() As String
            Get
                Return Me.zipCodeField
            End Get
            Set(value As String)
                Me.zipCodeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordIndicativeSocialSecurity

        Private numberField As String

        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductSubjectSubjectRecordAddOnProduct

        Private codeField As String

        Private scoreModelProductField As Boolean

        'Private creditorContactField As String

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property scoreModelProduct() As Boolean
            Get
                Return Me.scoreModelProductField
            End Get
            Set(value As Boolean)
                Me.scoreModelProductField = value
            End Set
        End Property

        'Public Property creditorContact() As String
        '    Get
        '        Return Me.creditorContactField
        '    End Get
        '    Set(value As String)
        '        Me.creditorContactField = value
        '    End Set
        'End Property

    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductResponseInstructions

        Private returnErrorTextField As Boolean

        Private documentField As String

        '''<remarks/>
        Public Property returnErrorText() As Boolean
            Get
                Return Me.returnErrorTextField
            End Get
            Set(value As Boolean)
                Me.returnErrorTextField = value
            End Set
        End Property

        '''<remarks/>
        Public Property document() As String
            Get
                Return Me.documentField
            End Get
            Set(value As String)
                Me.documentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductPermissiblePurpose

        Private inquiryECOADesignatorField As String
        Private codeField As String

        '''<remarks/>
        Public Property inquiryECOADesignator() As String
            Get
                Return Me.inquiryECOADesignatorField
            End Get
            Set(value As String)
                Me.inquiryECOADesignatorField = value
            End Set
        End Property

        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(ByVal value As String)
                Me.codeField = value
            End Set
        End Property
    End Class

End Namespace