'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

Namespace TUXML.Response.Error


    '
    'This source code was auto-generated by xsd, Version=4.0.30319.17929.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2"),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://api.creditly.co/v2", IsNullable:=False)>
    Partial Public Class creditBureau

        Private documentField As String

        Private versionField As Decimal

        Private transactionControlField As creditBureauTransactionControl

        Private productField As creditBureauProduct

        '''<remarks/>
        Public Property document() As String
            Get
                Return Me.documentField
            End Get
            Set(value As String)
                Me.documentField = value
            End Set
        End Property

        '''<remarks/>
        Public Property version() As Decimal
            Get
                Return Me.versionField
            End Get
            Set(value As Decimal)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property transactionControl() As creditBureauTransactionControl
            Get
                Return Me.transactionControlField
            End Get
            Set(value As creditBureauTransactionControl)
                Me.transactionControlField = value
            End Set
        End Property

        '''<remarks/>
        Public Property product() As creditBureauProduct
            Get
                Return Me.productField
            End Get
            Set(value As creditBureauProduct)
                Me.productField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControl

        Private userRefNumberField As String

        Private subscriberField As creditBureauTransactionControlSubscriber

        Private optionsField As creditBureauTransactionControlOptions

        Private trackingField As creditBureauTransactionControlTracking

        '''<remarks/>
        Public Property userRefNumber() As String
            Get
                Return Me.userRefNumberField
            End Get
            Set(value As String)
                Me.userRefNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property subscriber() As creditBureauTransactionControlSubscriber
            Get
                Return Me.subscriberField
            End Get
            Set(value As creditBureauTransactionControlSubscriber)
                Me.subscriberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property options() As creditBureauTransactionControlOptions
            Get
                Return Me.optionsField
            End Get
            Set(value As creditBureauTransactionControlOptions)
                Me.optionsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property tracking() As creditBureauTransactionControlTracking
            Get
                Return Me.trackingField
            End Get
            Set(value As creditBureauTransactionControlTracking)
                Me.trackingField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControlSubscriber

        Private industryCodeField As String

        Private memberCodeField As String

        Private inquirySubscriberPrefixCodeField As String

        '''<remarks/>
        Public Property industryCode() As String
            Get
                Return Me.industryCodeField
            End Get
            Set(value As String)
                Me.industryCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property memberCode() As String
            Get
                Return Me.memberCodeField
            End Get
            Set(value As String)
                Me.memberCodeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property inquirySubscriberPrefixCode() As String
            Get
                Return Me.inquirySubscriberPrefixCodeField
            End Get
            Set(value As String)
                Me.inquirySubscriberPrefixCodeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControlOptions

        Private countryField As String

        Private languageField As String

        '''<remarks/>
        Public Property country() As String
            Get
                Return Me.countryField
            End Get
            Set(value As String)
                Me.countryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set(value As String)
                Me.languageField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauTransactionControlTracking

        Private transactionTimeStampField As String

        '''<remarks/>
        Public Property transactionTimeStamp() As String
            Get
                Return Me.transactionTimeStampField
            End Get
            Set(value As String)
                Me.transactionTimeStampField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProduct

        Private codeField As String

        Private errorField As creditBureauProductError

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property [error]() As creditBureauProductError
            Get
                Return Me.errorField
            End Get
            Set(value As creditBureauProductError)
                Me.errorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://api.creditly.co/v2")>
    Partial Public Class creditBureauProductError

        Private subjectNumberField As String

        Private codeField As String

        Private descriptionField As String

        '''<remarks/>
        Public Property subjectNumber() As String
            Get
                Return Me.subjectNumberField
            End Get
            Set(value As String)
                Me.subjectNumberField = value
            End Set
        End Property

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set(value As String)
                Me.descriptionField = value
            End Set
        End Property
    End Class

End Namespace
