CREATE TABLE [dbo].[tblClientIntakeform](
	[ClientIntakeId] [int] IDENTITY(1,1) NOT NULL,
	[AccountID] [int] NULL,
	[CreditorInstanceID] [int] NULL,
	[IntakeFormDate] [datetime] NULL,
	[LitigationDocument] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Amount] [money] NULL,
	[ClientDocReceivedDate] [datetime] NULL,
	[HowDocReceived] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPlaintiffCompany] [bit] NULL,
	[IsAmountDispute] [bit] NULL,
	[IsRealestateOwner] [bit] NULL,
	[IsCurrentlyWorking] [bit] NULL,
	[AnyAccount] [bit] NULL,
	[HaveBankAccs] [bit] NULL,
	[HaveOtherAssets] [bit] NULL,
	[DeclinedLegalServices] [bit] NULL,
	[SentLocalCounsel] [bit] NULL,
	[Notes] [nvarchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsresidenceofPropertyOne] [bit] NULL,
	[DurationOwnerdPropertyOne] [int] NULL,
	[AppMarketvalPropertyOne] [decimal](18, 0) NULL,
	[PayoffPropertyOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LiensOnPropertyOne] [bit] NULL,
	[TotalEquityPropertyOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HousePaymentsPropertyOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PeopleLivePropertyOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsresidenceofPropertyTwo] [bit] NULL,
	[DurationOwnerdPropertyTwo] [int] NULL,
	[AppMarketvalPropertyTwo] [decimal](18, 0) NULL,
	[PayoffPropertyTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LiensOnPropertyTwo] [bit] NULL,
	[TotalEquityPropertyTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HousePaymentsPropertyTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PeopleLivePropertyTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployerName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrentEmployerDuration] [int] NULL,
	[Takehomepay] [money] NULL,
	[Per] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Otherwage] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OtherIncomeSource] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAccOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAmtSourceAccOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AppBalanceAccOne] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAccTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAmtSourceAccTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AppBalanceAccTwo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAccThree] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAmtSourceAccThree] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AppBalanceAccThree] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LegalServicesClientID] [int] NULL,
	[IsVerified] [bit] NULL,
	[VerifiedBy] [int] NULL,
	[VerifiedDate] [datetime] NULL,
	[FeePaidBy] [int] NULL,
	[IsReceivingAid] [bit] NULL,
	[TypeOfAid] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDatetime] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[LastModifiedDatetime] [datetime] NULL,
	[LastModifiedBy] [int] NULL,
	[AccTypeOne] [int] NULL,
	[AccTypeTwo] [int] NULL,
	[IsSelfEmployed] [bit] NULL,
	[Assets] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRentalPropertyOne] [bit] NULL,
	[RentOnPropertyOne] [money] NULL,
	[IsRentalPropertyTwo] [bit] NULL,
	[RentOnPropertyTwo] [money] NULL,
 CONSTRAINT [PK_tblClientIntakeform] PRIMARY KEY CLUSTERED 
(
	[ClientIntakeId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF